/* GENERATED by packages/i18n/tools/compile.ts — DO NOT EDIT.
 * Regenerate with `scripts/dev pnpm --filter @kinvara/i18n build`.
 * `build:check` fails if this file and the catalogues have drifted. */

import type { MessageFormatElement } from '@formatjs/icu-messageformat-parser';
import { formatAst } from '../../src/runtime.ts';

export const locale = 'en';
export const namespace = 'booking';

const a0 = [
  { type: 0, value: 'Cancelling now costs ' },
  {
    type: 2,
    value: 'fee',
    style: {
      type: 0,
      tokens: [{ stem: 'currency', options: ['EUR'] }],
      parsedOptions: { style: 'currency', currency: 'EUR' },
    },
  },
  { type: 0, value: '.' },
] as unknown as readonly MessageFormatElement[];
const a1 = [
  {
    type: 6,
    value: 'count',
    options: {
      one: { value: [{ type: 7 }, { type: 0, value: ' upcoming booking' }] },
      other: { value: [{ type: 7 }, { type: 0, value: ' upcoming bookings' }] },
    },
    offset: 0,
    pluralType: 'cardinal',
  },
] as unknown as readonly MessageFormatElement[];

export const messages = {
  'booking.cancel.fee_notice': (params: { readonly fee: number }): string =>
    formatAst(a0, locale, params),
  'booking.count.upcoming': (params: { readonly count: number }): string =>
    formatAst(a1, locale, params),
};
