/* GENERATED by packages/i18n/tools/compile.ts — DO NOT EDIT.
 * Regenerate with `scripts/dev pnpm --filter @kinvara/i18n build`.
 * `build:check` fails if this file and the catalogues have drifted. */

import type { MessageFormatElement } from '@formatjs/icu-messageformat-parser';
import { formatAst } from '../../src/runtime.ts';

export const locale = 'en';
export const namespace = 'notify';

const a0 = [
  { type: 0, value: 'Check in for your sit with ' },
  { type: 1, value: 'familyName' },
  { type: 0, value: '. It is due at ' },
  { type: 1, value: 'dueAt' },
  { type: 0, value: '.' },
] as unknown as readonly MessageFormatElement[];
const a1 = [
  { type: 0, value: 'Your week with Kinvara' },
] as unknown as readonly MessageFormatElement[];

export const messages = {
  'notify.checkin.reminder': (params: {
    readonly dueAt: string;
    readonly familyName: string;
  }): string => formatAst(a0, locale, params),
  'notify.digest.weekly_subject': (): string => formatAst(a1, locale, {}),
};
