/* GENERATED by packages/i18n/tools/compile.ts — DO NOT EDIT.
 * Regenerate with `scripts/dev pnpm --filter @kinvara/i18n build`.
 * `build:check` fails if this file and the catalogues have drifted. */

import type { MessageFormatElement } from '@formatjs/icu-messageformat-parser';
import { formatAst } from '../../src/runtime.ts';

export const locale = 'en';
export const namespace = 'safety';

const a0 = [
  { type: 0, value: 'Read this address to the 112 operator: ' },
  { type: 1, value: 'address' },
] as unknown as readonly MessageFormatElement[];
const a1 = [
  { type: 0, value: 'Call 112 — ambulance, police, fire' },
] as unknown as readonly MessageFormatElement[];
const a2 = [
  { type: 0, value: 'Say: “The address is ' },
  { type: 1, value: 'address' },
  { type: 0, value: '.” Then say what is happening and where you are. Do not hang up.' },
] as unknown as readonly MessageFormatElement[];
const a3 = [
  { type: 0, value: '116 111 — helpline for children and young people' },
] as unknown as readonly MessageFormatElement[];
const a4 = [
  { type: 0, value: '1466 — Hope For Children helpline' },
] as unknown as readonly MessageFormatElement[];
const a5 = [
  { type: 0, value: '199 — alternative emergency number' },
] as unknown as readonly MessageFormatElement[];
const a6 = [
  {
    type: 0,
    value:
      'Send SOS? This opens a call to 112 and shows the address to read out. Kinvara will be alerted.',
  },
] as unknown as readonly MessageFormatElement[];

export const messages = {
  'safety.emergency.address_prompt': (params: { readonly address: string }): string =>
    formatAst(a0, locale, params),
  'safety.emergency.call_112.label': (): string => formatAst(a1, locale, {}),
  'safety.emergency.call_112.script': (params: { readonly address: string }): string =>
    formatAst(a2, locale, params),
  'safety.helpline.116111.label': (): string => formatAst(a3, locale, {}),
  'safety.helpline.1466.label': (): string => formatAst(a4, locale, {}),
  'safety.helpline.199.label': (): string => formatAst(a5, locale, {}),
  'safety.sos.confirm': (): string => formatAst(a6, locale, {}),
};
