/**
 * The generated header of `db/schema.ts` — T-138 (tech-lead).
 *
 * `scripts/db-introspect.ts` writes `db/schema.ts` as three header lines followed by
 * drizzle-kit's `schema.ts`, byte for byte. The third header line carries the sha256 of
 * that body.
 *
 * Two readers:
 *   - `db:introspect:check` renders a fresh file and compares it with the committed one
 *     (the parity check, which needs a database), and verifies the committed header.
 *   - `gate:migration-lint` (static, no database) uses `verifySchemaFile` to let R-CONTRACT-ALONE
 *     accept `db/schema.ts` beside a contract migration only when the file is the generator's
 *     untouched output (OD-80).
 *
 * WHAT THE DIGEST PROVES, AND WHAT IT DOES NOT. A matching digest proves the body has not changed
 * since a header was computed for it. It does not prove the body came from drizzle-kit, nor that
 * it matches any database: anyone can recompute the digest over an edited body. Parity with the
 * database is `db:introspect:check`'s, and only that.
 */
import { createHash } from 'node:crypto';

export const SCHEMA_REL = 'db/schema.ts';

const LINE1 =
  '// GENERATED by `pnpm run db:introspect` (T-138, SD §DB-1) from a database with every committed';
const LINE2 =
  '// migration applied. Do not edit it: `pnpm run db:introspect:check` fails on any difference.';
const MARK = /^\/\/ @generated drizzle-kit (\S+) sha256:([0-9a-f]{64})$/;

export function digestOf(body: string): string {
  return createHash('sha256').update(body, 'utf8').digest('hex');
}

/** The whole file: the three header lines, then drizzle-kit's schema.ts unchanged. */
export function renderSchemaFile(body: string, drizzleKitVersion: string): string {
  return `${LINE1}\n${LINE2}\n// @generated drizzle-kit ${drizzleKitVersion} sha256:${digestOf(body)}\n${body}`;
}

export type SchemaFileVerdict =
  | { readonly ok: true; readonly drizzleKitVersion: string }
  | { readonly ok: false; readonly reason: string };

/** Is this text a generated header over a body whose sha256 it states? */
export function verifySchemaFile(text: string): SchemaFileVerdict {
  const lines = text.split('\n');
  if (lines.length < 4) return { ok: false, reason: 'shorter than the generated header' };
  if (lines[0] !== LINE1 || lines[1] !== LINE2) {
    return { ok: false, reason: 'the generated header is missing or has been edited' };
  }
  const m = MARK.exec(lines[2] ?? '');
  const version = m?.[1];
  const stated = m?.[2];
  if (version === undefined || stated === undefined) {
    return {
      ok: false,
      reason: 'no `// @generated drizzle-kit <version> sha256:<64 hex>` line under the header',
    };
  }
  const body = lines.slice(3).join('\n');
  if (digestOf(body) !== stated) {
    return {
      ok: false,
      reason: 'the body does not match the sha256 in its header: it was edited after generation',
    };
  }
  return { ok: true, drizzleKitVersion: version };
}
