/* GENERATED by packages/i18n/tools/compile.ts — DO NOT EDIT.
 * Regenerate with `scripts/dev pnpm --filter @kinvara/i18n build`.
 * `build:check` fails if this file and the catalogues have drifted. */

import type { MessageFunction } from '../src/runtime.ts';
import type { StrictMessageKey } from './tiers.ts';
import { messages as en } from './en/index.ts';
import { messages as el } from './el/index.ts';
import { messages as ru } from './ru/index.ts';

/** Every compiled catalogue, keyed by locale code. */
export const CATALOGUES: Readonly<Record<string, Readonly<Record<string, MessageFunction>>>> = {
  en,
  el,
  ru,
};

/**
 * SD §FE-10: "a missing key is a missing function and the build does not link."
 *
 * This declaration IS that mechanism. Every registered locale must supply
 * every `safety_critical` and `transactional` key; a gap is a missing property
 * on this object literal and `pnpm -w typecheck` fails, naming the locale and
 * the key. It is deliberately scoped to the two strict tiers — `operational`
 * and `marketing` keys ARE permitted to fall back to the default locale at run
 * time (SA §TS-12.1), and a type that forbade that would contradict the spec.
 */
export const STRICT_TIER_COMPLETENESS: Readonly<
  Record<string, Readonly<Record<StrictMessageKey, MessageFunction>>>
> = { en, el, ru };
