/* GENERATED by packages/i18n/tools/compile.ts — DO NOT EDIT.
 * Regenerate with `scripts/dev pnpm --filter @kinvara/i18n build`.
 * `build:check` fails if this file and the catalogues have drifted. */

import type { LocaleDescriptor } from '../src/types.ts';

/* The locale set is DATA (SA §TS-12.2 rule 5). This module is generated from
 * locale-registry.json, which mirrors the `locale_registry` table. Adding a
 * locale is a row there — never a union type here. */
export const DEFAULT_LOCALE = 'en';

export const LOCALE_DESCRIPTORS: readonly LocaleDescriptor[] = [
  {
    code: 'en',
    endonym: 'English',
    direction: 'ltr',
    isSafetyLanguage: true,
    pluralCategories: ['one', 'other'],
    enabled: true,
  },
  {
    code: 'el',
    endonym: 'Ελληνικά',
    direction: 'ltr',
    isSafetyLanguage: true,
    pluralCategories: ['one', 'other'],
    enabled: true,
  },
  {
    code: 'ru',
    endonym: 'Русский',
    direction: 'ltr',
    isSafetyLanguage: true,
    pluralCategories: ['one', 'few', 'many', 'other'],
    enabled: true,
  },
];
