/* GENERATED by packages/i18n/tools/compile.ts — DO NOT EDIT.
 * Regenerate with `scripts/dev pnpm --filter @kinvara/i18n build`.
 * `build:check` fails if this file and the catalogues have drifted. */

import type { Tier } from '../src/types.ts';

/** Every fully-qualified key known to the catalogues. */
export type MessageKey =
  | 'booking.cancel.fee_notice'
  | 'booking.count.upcoming'
  | 'common.app.name'
  | 'common.dossier.verified'
  | 'common.fallback.not_translated'
  | 'common.locale.switch_prompt'
  | 'common.marketing.tagline'
  | 'legal.terms.accept'
  | 'notify.checkin.reminder'
  | 'notify.digest.weekly_subject'
  | 'safety.emergency.address_prompt'
  | 'safety.emergency.call_112.label'
  | 'safety.emergency.call_112.script'
  | 'safety.helpline.116111.label'
  | 'safety.helpline.1466.label'
  | 'safety.helpline.199.label'
  | 'safety.sos.confirm'
  | 'session.checkins_missed'
  | 'session.staffed_hours.commitment';

/**
 * Keys whose tier has NO runtime fallback path (SA §TS-12.1, SD §FE-10):
 * `safety_critical` and `transactional`. `compiled/index.ts` asserts that
 * every registered locale supplies all of them, so a gap is a missing
 * property and the repo-wide typecheck does not link.
 */
export type StrictMessageKey =
  | 'booking.cancel.fee_notice'
  | 'booking.count.upcoming'
  | 'common.dossier.verified'
  | 'common.fallback.not_translated'
  | 'legal.terms.accept'
  | 'safety.emergency.address_prompt'
  | 'safety.emergency.call_112.label'
  | 'safety.emergency.call_112.script'
  | 'safety.helpline.116111.label'
  | 'safety.helpline.1466.label'
  | 'safety.helpline.199.label'
  | 'safety.sos.confirm'
  | 'session.checkins_missed'
  | 'session.staffed_hours.commitment';

export const TIERS: Readonly<Record<MessageKey, Tier>> = {
  'booking.cancel.fee_notice': 'transactional',
  'booking.count.upcoming': 'transactional',
  'common.app.name': 'marketing',
  'common.dossier.verified': 'transactional',
  'common.fallback.not_translated': 'transactional',
  'common.locale.switch_prompt': 'operational',
  'common.marketing.tagline': 'marketing',
  'legal.terms.accept': 'transactional',
  'notify.checkin.reminder': 'operational',
  'notify.digest.weekly_subject': 'operational',
  'safety.emergency.address_prompt': 'safety_critical',
  'safety.emergency.call_112.label': 'safety_critical',
  'safety.emergency.call_112.script': 'safety_critical',
  'safety.helpline.116111.label': 'safety_critical',
  'safety.helpline.1466.label': 'safety_critical',
  'safety.helpline.199.label': 'safety_critical',
  'safety.sos.confirm': 'safety_critical',
  'session.checkins_missed': 'safety_critical',
  'session.staffed_hours.commitment': 'transactional',
};
