/* GENERATED by packages/i18n/tools/compile.ts — DO NOT EDIT.
 * Regenerate with `scripts/dev pnpm --filter @kinvara/i18n build`.
 * `build:check` fails if this file and the catalogues have drifted. */

import type { MessageFormatElement } from '@formatjs/icu-messageformat-parser';
import { formatAst } from '../../src/runtime.ts';

export const locale = 'el';
export const namespace = 'common';

const a0 = [{ type: 0, value: 'Kinvara' }] as unknown as readonly MessageFormatElement[];
const a1 = [
  {
    type: 5,
    value: 'grammaticalRef',
    options: {
      feminine: { value: [{ type: 0, value: 'Επαληθευμένη' }] },
      masculine: { value: [{ type: 0, value: 'Επαληθευμένος' }] },
      other: { value: [{ type: 0, value: 'Επαληθευμένο' }] },
    },
  },
  { type: 0, value: ' στις ' },
  { type: 3, value: 'date', style: 'long' },
] as unknown as readonly MessageFormatElement[];
const a2 = [
  { type: 0, value: 'Αυτή η σελίδα δεν είναι ακόμη διαθέσιμη στα ελληνικά.' },
] as unknown as readonly MessageFormatElement[];
const a3 = [
  { type: 0, value: 'Να χρησιμοποιείται πάντα η γλώσσα ' },
  { type: 1, value: 'endonym' },
  { type: 0, value: ';' },
] as unknown as readonly MessageFormatElement[];

export const messages = {
  'common.app.name': (): string => formatAst(a0, locale, {}),
  'common.dossier.verified': (params: {
    readonly date: Date | number;
    readonly grammaticalRef: 'feminine' | 'masculine' | 'other';
  }): string => formatAst(a1, locale, params),
  'common.fallback.not_translated': (): string => formatAst(a2, locale, {}),
  'common.locale.switch_prompt': (params: { readonly endonym: string }): string =>
    formatAst(a3, locale, params),
};
