/* GENERATED by packages/i18n/tools/compile.ts — DO NOT EDIT.
 * Regenerate with `scripts/dev pnpm --filter @kinvara/i18n build`.
 * `build:check` fails if this file and the catalogues have drifted. */

import { messages as booking } from './booking.ts';
import { messages as common } from './common.ts';
import { messages as legal } from './legal.ts';
import { messages as notify } from './notify.ts';
import { messages as safety } from './safety.ts';
import { messages as session } from './session.ts';

export const locale = 'el';

export const messages = { ...booking, ...common, ...legal, ...notify, ...safety, ...session };
