/* GENERATED by packages/i18n/tools/compile.ts — DO NOT EDIT.
 * Regenerate with `scripts/dev pnpm --filter @kinvara/i18n build`.
 * `build:check` fails if this file and the catalogues have drifted. */

import type { MessageFormatElement } from '@formatjs/icu-messageformat-parser';
import { formatAst } from '../../src/runtime.ts';

export const locale = 'el';
export const namespace = 'legal';

const a0 = [
  { type: 0, value: 'Αποδέχομαι το έγγραφο ' },
  { type: 1, value: 'documentKind' },
  { type: 0, value: ', έκδοση ' },
  { type: 1, value: 'version' },
  { type: 0, value: '.' },
] as unknown as readonly MessageFormatElement[];

export const messages = {
  'legal.terms.accept': (params: {
    readonly documentKind: string;
    readonly version: string;
  }): string => formatAst(a0, locale, params),
};
