/* GENERATED by packages/i18n/tools/compile.ts — DO NOT EDIT.
 * Regenerate with `scripts/dev pnpm --filter @kinvara/i18n build`.
 * `build:check` fails if this file and the catalogues have drifted. */

import type { MessageFormatElement } from '@formatjs/icu-messageformat-parser';
import { formatAst } from '../../src/runtime.ts';

export const locale = 'el';
export const namespace = 'session';

const a0 = [
  { type: 1, value: 'sitterName' },
  { type: 0, value: ': ' },
  {
    type: 6,
    value: 'count',
    options: {
      one: {
        value: [
          { type: 0, value: 'δεν έχουμε λάβει ' },
          { type: 7 },
          { type: 0, value: ' επιβεβαίωση «Όλα καλά»' },
        ],
      },
      other: {
        value: [
          { type: 0, value: 'δεν έχουμε λάβει ' },
          { type: 7 },
          { type: 0, value: ' επιβεβαιώσεις «Όλα καλά»' },
        ],
      },
    },
    offset: 0,
    pluralType: 'cardinal',
  },
] as unknown as readonly MessageFormatElement[];
const a1 = [
  {
    type: 0,
    value:
      'Εκπαιδευμένο στέλεχος προστασίας παιδιών είναι σε βάρδια για κάθε λεπτό κάθε φύλαξης και για μία ώρα μετά το τέλος της.',
  },
] as unknown as readonly MessageFormatElement[];

export const messages = {
  'session.checkins_missed': (params: {
    readonly count: number;
    readonly sitterName: string;
  }): string => formatAst(a0, locale, params),
  'session.staffed_hours.commitment': (): string => formatAst(a1, locale, {}),
};
