// GENERATED by `pnpm run db:introspect` (T-138, SD §DB-1) from a database with every committed
// migration applied. Do not edit it: `pnpm run db:introspect:check` fails on any difference.
// @generated drizzle-kit 0.31.10 sha256:5c502581a54a30ea55c7592f06f92232281513d78e6db3632fe523d02bf67b9e
import { pgTable } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"




