// GENERATED by `pnpm run db:introspect` (T-138, SD §DB-1) from a database with every committed
// migration applied. Do not edit it: `pnpm run db:introspect:check` fails on any difference.
// @generated drizzle-kit 0.31.10 sha256:8427ffd4e70fd165850afc3d3d0e1e7e0a4547155ce497fc5fcba71827456e6f
import { pgTable, check, text, boolean } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const localeRegistry = pgTable("locale_registry", {
	code: text().primaryKey().notNull(),
	endonym: text().notNull(),
	direction: text().default('ltr').notNull(),
	isSafetyLanguage: boolean("is_safety_language").notNull(),
	pluralCategories: text("plural_categories").array().notNull(),
	enabled: boolean().default(true).notNull(),
}, (table) => [
	check("locale_registry_direction_check", sql`direction = ANY (ARRAY['ltr'::text, 'rtl'::text])`),
]);
