// GENERATED by `pnpm run db:introspect` (T-138, SD §DB-1) from a database with every committed
// migration applied. Do not edit it: `pnpm run db:introspect:check` fails on any difference.
// @generated drizzle-kit 0.31.10 sha256:e27210bac6541c12005b43801bbc1684a44d69d919169bf377fd16153d11cb8b
import { boolean, char, check, customType, foreignKey, index, inet, pgEnum, pgTable, primaryKey, text, timestamp, unique, uniqueIndex } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"

// Column types drizzle-kit cannot render, mapped by scripts/gates/lib/schema-render.ts (T-150).
const citext = customType<{ data: string; driverData: string }>({ dataType() { return "citext"; } });
const bytea = customType<{ data: Buffer; driverData: Buffer }>({ dataType() { return "bytea"; } });

export const accountStatus = pgEnum("account_status", ['pending', 'active', 'suspended', 'removed', 'erased'])


export const account = pgTable("account", {
	id: char({ length: 26 }).primaryKey().notNull(),
	emailCi: citext("email_ci"),
	emailVerifiedAt: timestamp("email_verified_at", { withTimezone: true, mode: 'string' }),
	phoneE164: text("phone_e164"),
	phoneVerifiedAt: timestamp("phone_verified_at", { withTimezone: true, mode: 'string' }),
	passwordHash: text("password_hash"),
	status: accountStatus().default('pending').notNull(),
	pseudonym: char({ length: 26 }).notNull(),
	jurisdiction: text().default('CY').notNull(),
	dataRegion: text("data_region").default('eu-central-1').notNull(),
	locale: text().default('en').notNull(),
	localeSource: text("locale_source").default('inferred').notNull(),
	localeSetAt: timestamp("locale_set_at", { withTimezone: true, mode: 'string' }),
	grammaticalReference: text("grammatical_reference").default('other').notNull(),
	tosVersion: text("tos_version").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	erasedAt: timestamp("erased_at", { withTimezone: true, mode: 'string' }),
	dobVerified18: boolean("dob_verified_18").default(false).notNull(),
}, (table) => [
	foreignKey({
			columns: [table.locale],
			foreignColumns: [localeRegistry.code],
			name: "account_locale_fkey"
		}),
	unique("account_email_ci_key").on(table.emailCi),
	unique("account_phone_e164_key").on(table.phoneE164),
	unique("account_pseudonym_key").on(table.pseudonym),
	check("account_grammatical_reference_check", sql`grammatical_reference = ANY (ARRAY['feminine'::text, 'masculine'::text, 'other'::text])`),
	check("account_locale_source_check", sql`locale_source = ANY (ARRAY['inferred'::text, 'chosen'::text])`),
	check("account_min_age_verified", sql`(status <> 'active'::account_status) OR (dob_verified_18 IS TRUE)`),
]);

export const accountRole = pgTable("account_role", {
	accountId: char("account_id", { length: 26 }).notNull(),
	role: text().notNull(),
	grantedBy: char("granted_by", { length: 26 }),
	grantedAt: timestamp("granted_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	revokedAt: timestamp("revoked_at", { withTimezone: true, mode: 'string' }),
}, (table) => [
	uniqueIndex("sod_finance_ts").using("btree", table.accountId.asc().nullsLast().op("bpchar_ops")).where(sql`((role = ANY (ARRAY['finance'::text, 'ts_operator'::text])) AND (revoked_at IS NULL))`),
	foreignKey({
			columns: [table.accountId],
			foreignColumns: [account.id],
			name: "account_role_account_id_fkey"
		}).onDelete("cascade"),
	primaryKey({ columns: [table.accountId, table.role], name: "account_role_pkey"}),
	check("account_role_role_check", sql`role = ANY (ARRAY['parent'::text, 'sitter'::text, 'support'::text, 'ts_operator'::text, 'ts_senior'::text, 'dsl'::text, 'deputy_dsl'::text, 'finance'::text, 'compliance'::text, 'engineer'::text])`),
]);

export const appSession = pgTable("app_session", {
	id: char({ length: 26 }).primaryKey().notNull(),
	tokenHash: bytea("token_hash").notNull(),
	accountId: char("account_id", { length: 26 }).notNull(),
	authMethod: text("auth_method").notNull(),
	deviceFingerprint: text("device_fingerprint"),
	ipPrefix: inet("ip_prefix"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	lastSeenAt: timestamp("last_seen_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	absoluteExpiresAt: timestamp("absolute_expires_at", { withTimezone: true, mode: 'string' }).notNull(),
	stepUpUntil: timestamp("step_up_until", { withTimezone: true, mode: 'string' }),
	revokedAt: timestamp("revoked_at", { withTimezone: true, mode: 'string' }),
	revokedReason: text("revoked_reason"),
}, (table) => [
	index("app_session_account_id_idx").using("btree", table.accountId.asc().nullsLast().op("bpchar_ops")).where(sql`(revoked_at IS NULL)`),
	foreignKey({
			columns: [table.accountId],
			foreignColumns: [account.id],
			name: "app_session_account_id_fkey"
		}).onDelete("cascade"),
	unique("app_session_token_hash_key").on(table.tokenHash),
	check("app_session_auth_method_check", sql`auth_method = ANY (ARRAY['password'::text, 'magic_link'::text, 'passkey'::text, 'otp'::text, 'sso'::text])`),
]);

export const approval = pgTable("approval", {
	id: char({ length: 26 }).primaryKey().notNull(),
	subjectType: text("subject_type").notNull(),
	subjectId: char("subject_id", { length: 26 }).notNull(),
	action: text().notNull(),
	submitterId: char("submitter_id", { length: 26 }).notNull(),
	submittedAt: timestamp("submitted_at", { withTimezone: true, mode: 'string' }).notNull(),
	approverId: char("approver_id", { length: 26 }),
	approvedAt: timestamp("approved_at", { withTimezone: true, mode: 'string' }),
	decision: text(),
	rationale: text(),
}, () => [
	check("approval_distinct_actors", sql`approver_id IS DISTINCT FROM submitter_id`),
]);

export const localeRegistry = pgTable("locale_registry", {
	code: text().primaryKey().notNull(),
	endonym: text().notNull(),
	direction: text().default('ltr').notNull(),
	isSafetyLanguage: boolean("is_safety_language").notNull(),
	pluralCategories: text("plural_categories").array().notNull(),
	enabled: boolean().default(true).notNull(),
}, () => [
	check("locale_registry_direction_check", sql`direction = ANY (ARRAY['ltr'::text, 'rtl'::text])`),
]);
