/* GENERATED by packages/i18n/tools/compile.ts — DO NOT EDIT.
 * Regenerate with `scripts/dev pnpm --filter @kinvara/i18n build`.
 * `build:check` fails if this file and the catalogues have drifted. */

import type { MessageFormatElement } from '@formatjs/icu-messageformat-parser';
import { formatAst } from '../../src/runtime.ts';

export const locale = 'ru';
export const namespace = 'safety';

const a0 = [
  { type: 0, value: 'Прочитайте этот адрес вслух оператору 112: ' },
  { type: 1, value: 'address' },
] as unknown as readonly MessageFormatElement[];
const a1 = [
  { type: 0, value: 'Позвонить в 112 — скорая, полиция, пожарные' },
] as unknown as readonly MessageFormatElement[];
const a2 = [
  { type: 0, value: 'Скажите: «Адрес: ' },
  { type: 1, value: 'address' },
  { type: 0, value: '». Затем расскажите, что происходит и где вы находитесь. Не кладите трубку.' },
] as unknown as readonly MessageFormatElement[];
const a3 = [
  { type: 0, value: '116 111 — линия помощи для детей и подростков' },
] as unknown as readonly MessageFormatElement[];
const a4 = [
  { type: 0, value: '1466 — линия помощи Hope For Children' },
] as unknown as readonly MessageFormatElement[];
const a5 = [
  { type: 0, value: '199 — альтернативный экстренный номер' },
] as unknown as readonly MessageFormatElement[];
const a6 = [
  {
    type: 0,
    value:
      'Отправить SOS? Откроется вызов 112, а на экране появится адрес, чтобы зачитать его вслух. Kinvara получит оповещение.',
  },
] as unknown as readonly MessageFormatElement[];

export const messages = {
  'safety.emergency.address_prompt': (params: { readonly address: string }): string =>
    formatAst(a0, locale, params),
  'safety.emergency.call_112.label': (): string => formatAst(a1, locale, {}),
  'safety.emergency.call_112.script': (params: { readonly address: string }): string =>
    formatAst(a2, locale, params),
  'safety.helpline.116111.label': (): string => formatAst(a3, locale, {}),
  'safety.helpline.1466.label': (): string => formatAst(a4, locale, {}),
  'safety.helpline.199.label': (): string => formatAst(a5, locale, {}),
  'safety.sos.confirm': (): string => formatAst(a6, locale, {}),
};
