/* GENERATED by packages/i18n/tools/compile.ts — DO NOT EDIT.
 * Regenerate with `scripts/dev pnpm --filter @kinvara/i18n build`.
 * `build:check` fails if this file and the catalogues have drifted. */

import type { MessageFormatElement } from '@formatjs/icu-messageformat-parser';
import { formatAst } from '../../src/runtime.ts';

export const locale = 'ru';
export const namespace = 'session';

const a0 = [
  {
    type: 6,
    value: 'count',
    options: {
      one: {
        value: [{ type: 0, value: 'Пропущена ' }, { type: 7 }, { type: 0, value: ' отметка' }],
      },
      few: {
        value: [{ type: 0, value: 'Пропущено ' }, { type: 7 }, { type: 0, value: ' отметки' }],
      },
      many: {
        value: [{ type: 0, value: 'Пропущено ' }, { type: 7 }, { type: 0, value: ' отметок' }],
      },
      other: {
        value: [{ type: 0, value: 'Пропущено ' }, { type: 7 }, { type: 0, value: ' отметки' }],
      },
    },
    offset: 0,
    pluralType: 'cardinal',
  },
  { type: 0, value: ' от ' },
  { type: 1, value: 'sitterName' },
] as unknown as readonly MessageFormatElement[];
const a1 = [
  {
    type: 0,
    value:
      'Обученный специалист по безопасности детей находится на смене каждую минуту каждой смены няни и ещё один час после её окончания.',
  },
] as unknown as readonly MessageFormatElement[];

export const messages = {
  'session.checkins_missed': (params: {
    readonly count: number;
    readonly sitterName: string;
  }): string => formatAst(a0, locale, params),
  'session.staffed_hours.commitment': (): string => formatAst(a1, locale, {}),
};
