/* GENERATED by packages/i18n/tools/compile.ts — DO NOT EDIT.
 * Regenerate with `scripts/dev pnpm --filter @kinvara/i18n build`.
 * `build:check` fails if this file and the catalogues have drifted. */

import type { MessageFormatElement } from '@formatjs/icu-messageformat-parser';
import { formatAst } from '../../src/runtime.ts';

export const locale = 'ru';
export const namespace = 'session';

const a0 = [
  { type: 0, value: 'Мы не получили ' },
  {
    type: 6,
    value: 'count',
    options: {
      one: { value: [{ type: 7 }, { type: 0, value: ' отметку' }] },
      few: { value: [{ type: 7 }, { type: 0, value: ' отметки' }] },
      many: { value: [{ type: 7 }, { type: 0, value: ' отметок' }] },
      other: { value: [{ type: 7 }, { type: 0, value: ' отметки' }] },
    },
    offset: 0,
    pluralType: 'cardinal',
  },
  { type: 0, value: ' от няни ' },
  { type: 1, value: 'sitterName' },
] as unknown as readonly MessageFormatElement[];
const a1 = [
  {
    type: 0,
    value:
      'На протяжении каждой смены няни — от первой до последней минуты — и ещё час после её окончания дежурит обученный специалист по защите детей.',
  },
] as unknown as readonly MessageFormatElement[];

export const messages = {
  'session.checkins_missed': (params: {
    readonly count: number;
    readonly sitterName: string;
  }): string => formatAst(a0, locale, params),
  'session.staffed_hours.commitment': (): string => formatAst(a1, locale, {}),
};
